### ISSUE TITLE
ENOTFOUND or ECONNREFUSED for all client functions

### ISSUE THREAD

**Issue by rilkeanheart** [nodejitsu/node-cloudservers#12] opened 2012-01-28 07:05 UTC
Just installed node-cloudservers via npm today.  So far, I haven't been able to use any of the client functions to create a server on Rackspace.  All return an err of either ECONNREFUSED (when I'm at work) or ENOTFOUND (when I'm at home).  I'm using Mac OS Snow Leopard, and I found a similar issue reported a year ago related to the use of /etc/resolv.conf for dns lookup resolution.   Other functions (npm, curl, etc.) appear to work fine.  Is there something I'm missing?

**Comment by Marak** [comment] 2012-01-28 08:03
Can you paste the code you are attempting to run?

That error message is being thrown from node.js core, it generally means that your outgoing connection cannot find it's target ( bad URI / bad network / etc )

**Comment by rilkeanheart** [comment] 2012-01-28 13:10
Thanks Marak.  Here's the code I'm trying to run.

``` javascript
var cloudservers = require('cloudservers'),
    sys = require('sys');

function createServer(serverName, client) {
  var options = {
    name: serverName,
    image: 49, // Ubuntu 10.04 (Lucid Lynx)
    flavor: 1, // 256 server
  };

  client.setAuth(function (err, res) {
    if(err) {
      console.log("Error Authenticating Client:")
      console.log(err);
    } else {
      client.createServer(options, function (err, server) {
        if(err) {
          console.log("Error Creating Server")
          console.log(err);
        } else {
          server.setWait({ status: 'ACTIVE' }, 5000, function () {
            // Our server is now built and active, so we can install node.js on it
            sys.puts('Your server ' + serverName + ' is now ready.');
            sys.puts('  IP Address: ' + server.addresses.public);
            sys.puts('  Root password: ' + server.adminPass);
          });
        }
      });      
    }
  });
};

var args = process.argv.slice(2);
var serverName = args[0];
var username = args[1] || 'my-userid';
var apiKey = args[2] || 'my-api-key';

var config = {
  auth : {
    username: 'my-userid',
    apiKey: 'my-api-key'
  }
};

var client = cloudservers.createClient(config);

createServer(serverName, client);
```

I can successfully authenticate using curl with the following:

user$ curl -D - \
  -H "X-Auth-Key: (my-api-key)" \
  -H "X-Auth-User: (my-user-id)" \
  https://auth.api.rackspacecloud.com/v1.0

I agree with you.  Everything points to something funky with the outbound connection...but I don't seem to have issues with curl or npm.

**Comment by rilkeanheart** [comment] 2012-02-13 02:04
Haven't resolved.  Any ideas?

**Comment by CrypticSwarm** [comment] 2012-02-14 06:16
Confirmed the same problem.  I used the `client.getFlavors` example from the readme.

**Comment by CrypticSwarm** [comment] 2012-02-14 06:34
Seems the current git repo works.  What is in npm doesn't.  Might need to publish version "0.2.9". Current in npm in "0.2.8"

**Comment by kenperkins** [comment] 2012-04-09 18:26
Ditto on the npm installed version.

**Comment by pkrumins** [comment] 2012-04-17 20:01
Well I just had to use this library and the workaround is to set "host" to "auth.api.rackspacecloud.com" in the auth hash. The problem is within lib/cloudservers/code.js when in the setAuth function the `authUrl` becomes undefined for some reason. I tried debugging it but couldn't figure out why that happens.

Here is how you set the auth hash so it worked:

{
    "username" : "X",
    "apiKey" : "Y",
    "host" : "auth.api.rackspacecloud.com"
}

**Comment by pkrumins** [comment] 2012-04-17 20:15
Turns out this bug has been fixed in the current master, and it just hasn't been `npm publish`ed!

**Comment by crystalneth** [comment] 2012-06-17 19:28
Current master is broken in other ways. It does not properly set the serverUrl after authorization resulting in a protocol error. Any chance of getting a stable version pushed to npm?

UPDATE: My bad, I had an auth error, which instead of being reported or throwing an exception, just messes up the config hash by assuming a valid response.

**Closed as completed** 2012-07-19 06:22 UTC
